import type { ContentType } from './providers/types'

export const progressPattern: RegExp = /^(\d+)\s*\/\s*(\d+)$/
export const dmyDatePattern: RegExp = /^(\d{2})\.(\d{2})\.(\d{4})$/
export const localeMap: Record<string, SupportedLocale> = {
	ru: 'ru',
	de: 'de',
	es: 'es',
	fr: 'fr',
	zh: 'zh',
	ar: 'ar',
	he: 'he'
}

export type SupportedLocale = 'en' | 'ru' | 'de' | 'es' | 'fr' | 'zh' | 'ar' | 'he'

export const I18N: Record<SupportedLocale, Record<string, string>> = {
	en: {
		'cmd.addContent': 'Add content',
		'cmd.refresh': 'Refresh metadata for current note',
		'cmd.searchLibrary': 'Search your library',
		'cmd.openLibrary': 'Open Library',
		'cmd.rebuildLinks': 'Rebuild graph links',
		'view.title': 'Library',
		'modal.pickType': 'Choose a category',
		'modal.search.placeholder': 'Search by title…',
		'modal.searchLibrary': 'Search your library…',
		'modal.noCategories': 'Add a category in settings first',
		'modal.manualTitle': 'New entry',
		'modal.manualCreate': 'Create',
		'notice.created': 'Created: {name}',
		'notice.notFound': 'Nothing found to update',
		'notice.searching': 'Fetching metadata…',
		'notice.linksRebuilt': 'Graph links rebuilt: {count}',
		'sort.name': 'A-Z',
		'sort.year': 'Year',
		'sort.rating': 'Rating',
		'sort.date': 'Date',
		'header.creator': 'Creator',
		'header.years': 'Years',
		'header.seasons': 'Seasons',
		'header.genre': 'Genre',
		'header.myRating': 'My Rating',
		'header.progress': 'Progress',
		'header.complete': 'Complete',
		'settings.intro':
			'Configure content categories. Open the Library tab from the ribbon to add content; notes are grouped into categories by their Type frontmatter field.',
		'settings.omdb.name': 'OMDb API key (optional)',
		'settings.omdb.desc':
			'Used to auto-fill IMDb rating and metadata for movies and series. Get a key at: https://www.omdbapi.com/apikey.aspx',
		'settings.omdb.placeholder': 'Example: a1b2c3d4',
		'settings.google.name': 'Google Books API key (optional)',
		'settings.google.desc':
			'Required for Google Books search — the keyless quota is shared and usually exhausted. Get a free key: enable the Books API at https://console.cloud.google.com/apis/library/books.googleapis.com',
		'settings.google.placeholder': 'Example: AIzaSy…',
		'settings.rawg.name': 'RAWG API key (for games)',
		'settings.rawg.desc':
			'Required for game search. Get a free key at: https://rawg.io/apidocs',
		'settings.rawg.placeholder': 'Example: 0a1b2c3d…',
		'settings.section.categories': 'Categories',
		'settings.categories.desc':
			'Each category shows notes whose Type frontmatter equals the value below.',
		'settings.category.name': 'Category {index}',
		'settings.category.desc': 'Display name, matching Type value, and source',
		'settings.category.name.placeholder': 'Name (e.g. Movies)',
		'settings.category.type.placeholder': 'Type (e.g. Movie)',
		'settings.category.folder': 'Folder',
		'settings.category.folder.placeholder': 'e.g. Media/Movies',
		'settings.category.manual': 'Manual · no source',
		'settings.addCategory': 'Add category',
		'settings.newCategory': 'New category',
		'settings.section.example': 'Example note',
		'settings.example.desc':
			'To include a note in a category, set the Type field in frontmatter.'
	},
	ru: {
		'cmd.addContent': 'Добавить контент',
		'cmd.refresh': 'Обновить метаданные текущей заметки',
		'cmd.searchLibrary': 'Поиск по библиотеке',
		'cmd.openLibrary': 'Открыть библиотеку',
		'cmd.rebuildLinks': 'Перестроить связи для графа',
		'view.title': 'Библиотека',
		'modal.pickType': 'Выберите категорию',
		'modal.search.placeholder': 'Поиск по названию…',
		'modal.searchLibrary': 'Поиск по библиотеке…',
		'modal.noCategories': 'Сначала добавьте категорию в настройках',
		'modal.manualTitle': 'Новая запись',
		'modal.manualCreate': 'Создать',
		'notice.created': 'Создано: {name}',
		'notice.notFound': 'Нечего обновлять',
		'notice.searching': 'Загрузка метаданных…',
		'notice.linksRebuilt': 'Связи для графа перестроены: {count}',
		'sort.name': 'А-Я',
		'sort.year': 'Год',
		'sort.rating': 'Рейтинг',
		'sort.date': 'Дата',
		'header.creator': 'Автор',
		'header.years': 'Годы',
		'header.seasons': 'Сезоны',
		'header.genre': 'Жанр',
		'header.myRating': 'Моя оценка',
		'header.progress': 'Прогресс',
		'header.complete': 'Завершено',
		'settings.intro':
			'Настройте категории контента. Открывайте вкладку «Библиотека» из бокового меню, чтобы добавлять контент; заметки группируются по полю Type во фронтматтере.',
		'settings.omdb.name': 'OMDb API ключ (необязательно)',
		'settings.omdb.desc':
			'Нужен для автозаполнения рейтинга IMDb и метаданных фильмов и сериалов. Получить ключ: https://www.omdbapi.com/apikey.aspx',
		'settings.omdb.placeholder': 'Например: a1b2c3d4',
		'settings.section.categories': 'Категории',
		'settings.categories.desc':
			'Каждая категория показывает заметки, где поле Type равно указанному значению.',
		'settings.category.name': 'Категория {index}',
		'settings.category.desc': 'Название, значение Type и источник',
		'settings.category.name.placeholder': 'Название (например: Фильмы)',
		'settings.category.type.placeholder': 'Type (например: Movie)',
		'settings.category.folder': 'Папка',
		'settings.category.folder.placeholder': 'напр. Media/Movies',
		'settings.category.manual': 'Вручную · без источника',
		'settings.addCategory': 'Добавить категорию',
		'settings.newCategory': 'Новая категория',
		'settings.section.example': 'Пример заметки',
		'settings.example.desc':
			'Чтобы заметка попала в категорию, укажите поле Type во фронтматтере.'
	},
	de: {
		'cmd.addContent': 'Inhalt hinzufügen',
		'cmd.refresh': 'Metadaten der aktuellen Notiz aktualisieren',
		'cmd.searchLibrary': 'Bibliothek durchsuchen',
		'cmd.openLibrary': 'Bibliothek öffnen',
		'cmd.rebuildLinks': 'Graph-Verknüpfungen neu aufbauen',
		'view.title': 'Bibliothek',
		'modal.pickType': 'Kategorie wählen',
		'modal.search.placeholder': 'Nach Titel suchen…',
		'modal.searchLibrary': 'Bibliothek durchsuchen…',
		'modal.noCategories': 'Füge zuerst eine Kategorie in den Einstellungen hinzu',
		'modal.manualTitle': 'Neuer Eintrag',
		'modal.manualCreate': 'Erstellen',
		'notice.created': 'Erstellt: {name}',
		'notice.notFound': 'Nichts zum Aktualisieren gefunden',
		'notice.searching': 'Metadaten werden geladen…',
		'notice.linksRebuilt': 'Graph-Verknüpfungen neu aufgebaut: {count}',
		'sort.name': 'A-Z',
		'sort.year': 'Jahr',
		'sort.rating': 'Bewertung',
		'sort.date': 'Datum',
		'header.creator': 'Autor',
		'header.years': 'Jahre',
		'header.seasons': 'Staffeln',
		'header.genre': 'Genre',
		'header.myRating': 'Meine Bewertung',
		'header.progress': 'Fortschritt',
		'header.complete': 'Abgeschlossen',
		'settings.intro':
			'Konfiguriere Inhaltskategorien. Öffne den Bibliothek-Tab über das Seitenmenü, um Inhalte hinzuzufügen; Notizen werden anhand des Frontmatter-Felds Type gruppiert.',
		'settings.omdb.name': 'OMDb-API-Schlüssel (optional)',
		'settings.omdb.desc':
			'Wird zum automatischen Ausfüllen der IMDb-Bewertung und Metadaten von Filmen und Serien verwendet. Schlüssel: https://www.omdbapi.com/apikey.aspx',
		'settings.omdb.placeholder': 'z. B. a1b2c3d4',
		'settings.section.categories': 'Kategorien',
		'settings.categories.desc':
			'Jede Kategorie zeigt Notizen, deren Frontmatter-Feld Type dem Wert entspricht.',
		'settings.category.name': 'Kategorie {index}',
		'settings.category.desc': 'Anzeigename, zugehöriger Type-Wert und Quelle',
		'settings.category.name.placeholder': 'Name (z. B. Filme)',
		'settings.category.type.placeholder': 'Type (z. B. Movie)',
		'settings.category.folder': 'Ordner',
		'settings.category.folder.placeholder': 'z. B. Media/Filme',
		'settings.category.manual': 'Manuell · keine Quelle',
		'settings.addCategory': 'Kategorie hinzufügen',
		'settings.newCategory': 'Neue Kategorie',
		'settings.section.example': 'Beispielnotiz',
		'settings.example.desc':
			'Damit eine Notiz in eine Kategorie fällt, setze das Type-Feld im Frontmatter.'
	},
	es: {
		'cmd.addContent': 'Agregar contenido',
		'cmd.refresh': 'Actualizar metadatos de la nota actual',
		'cmd.searchLibrary': 'Buscar en tu biblioteca',
		'cmd.openLibrary': 'Abrir biblioteca',
		'cmd.rebuildLinks': 'Reconstruir enlaces del grafo',
		'view.title': 'Biblioteca',
		'modal.pickType': 'Elige una categoría',
		'modal.search.placeholder': 'Buscar por título…',
		'modal.searchLibrary': 'Buscar en tu biblioteca…',
		'modal.noCategories': 'Primero añade una categoría en los ajustes',
		'modal.manualTitle': 'Nueva entrada',
		'modal.manualCreate': 'Crear',
		'notice.created': 'Creado: {name}',
		'notice.notFound': 'No hay nada que actualizar',
		'notice.searching': 'Obteniendo metadatos…',
		'notice.linksRebuilt': 'Enlaces del grafo reconstruidos: {count}',
		'sort.name': 'A-Z',
		'sort.year': 'Año',
		'sort.rating': 'Puntuación',
		'sort.date': 'Fecha',
		'header.creator': 'Creador',
		'header.years': 'Años',
		'header.seasons': 'Temporadas',
		'header.genre': 'Género',
		'header.myRating': 'Mi nota',
		'header.progress': 'Progreso',
		'header.complete': 'Completado',
		'settings.intro':
			'Configura las categorías de contenido. Abre la pestaña Biblioteca desde la barra lateral para agregar contenido; las notas se agrupan por el campo Type del frontmatter.',
		'settings.omdb.name': 'Clave OMDb API (opcional)',
		'settings.omdb.desc':
			'Se usa para autocompletar la puntuación de IMDb y metadatos de películas y series. Obtén la clave en https://www.omdbapi.com/apikey.aspx',
		'settings.omdb.placeholder': 'Ej: a1b2c3d4',
		'settings.section.categories': 'Categorías',
		'settings.categories.desc':
			'Cada categoría muestra notas cuyo campo Type coincide con el valor indicado.',
		'settings.category.name': 'Categoría {index}',
		'settings.category.desc': 'Nombre visible, valor de Type y fuente',
		'settings.category.name.placeholder': 'Nombre (p. ej. Películas)',
		'settings.category.type.placeholder': 'Type (p. ej. Movie)',
		'settings.category.folder': 'Carpeta',
		'settings.category.folder.placeholder': 'p. ej. Media/Películas',
		'settings.category.manual': 'Manual · sin fuente',
		'settings.addCategory': 'Agregar categoría',
		'settings.newCategory': 'Nueva categoría',
		'settings.section.example': 'Nota de ejemplo',
		'settings.example.desc':
			'Para incluir una nota en una categoría, define el campo Type en el frontmatter.'
	},
	fr: {
		'cmd.addContent': 'Ajouter du contenu',
		'cmd.refresh': 'Actualiser les métadonnées de la note',
		'cmd.searchLibrary': 'Rechercher dans la bibliothèque',
		'cmd.openLibrary': 'Ouvrir la bibliothèque',
		'cmd.rebuildLinks': 'Reconstruire les liens du graphe',
		'view.title': 'Bibliothèque',
		'modal.pickType': 'Choisir une catégorie',
		'modal.search.placeholder': 'Rechercher par titre…',
		'modal.searchLibrary': 'Rechercher dans la bibliothèque…',
		'modal.noCategories': 'Ajoutez d’abord une catégorie dans les paramètres',
		'modal.manualTitle': 'Nouvelle entrée',
		'modal.manualCreate': 'Créer',
		'notice.created': 'Créé : {name}',
		'notice.notFound': 'Rien à mettre à jour',
		'notice.searching': 'Récupération des métadonnées…',
		'notice.linksRebuilt': 'Liens du graphe reconstruits : {count}',
		'sort.name': 'A-Z',
		'sort.year': 'Année',
		'sort.rating': 'Note',
		'sort.date': 'Date',
		'header.creator': 'Créateur',
		'header.years': 'Années',
		'header.seasons': 'Saisons',
		'header.genre': 'Genre',
		'header.myRating': 'Ma note',
		'header.progress': 'Progression',
		'header.complete': 'Terminé',
		'settings.intro':
			'Configurez les catégories de contenu. Ouvrez l’onglet Bibliothèque depuis la barre latérale pour ajouter du contenu ; les notes sont regroupées selon le champ Type du frontmatter.',
		'settings.omdb.name': 'Clé OMDb API (optionnelle)',
		'settings.omdb.desc':
			'Permet de remplir automatiquement la note IMDb et les métadonnées des films et séries. Obtenez la clé sur https://www.omdbapi.com/apikey.aspx',
		'settings.omdb.placeholder': 'Ex : a1b2c3d4',
		'settings.section.categories': 'Catégories',
		'settings.categories.desc':
			'Chaque catégorie affiche les notes dont le champ Type correspond à la valeur ci-dessous.',
		'settings.category.name': 'Catégorie {index}',
		'settings.category.desc': 'Nom d’affichage, valeur Type et source',
		'settings.category.name.placeholder': 'Nom (p. ex. Films)',
		'settings.category.type.placeholder': 'Type (p. ex. Movie)',
		'settings.category.folder': 'Dossier',
		'settings.category.folder.placeholder': 'p. ex. Media/Films',
		'settings.category.manual': 'Manuel · sans source',
		'settings.addCategory': 'Ajouter une catégorie',
		'settings.newCategory': 'Nouvelle catégorie',
		'settings.section.example': 'Note d’exemple',
		'settings.example.desc':
			'Pour inclure une note dans une catégorie, renseignez le champ Type dans le frontmatter.'
	},
	zh: {
		'cmd.addContent': '添加内容',
		'cmd.refresh': '刷新当前笔记的元数据',
		'cmd.searchLibrary': '搜索你的库',
		'cmd.openLibrary': '打开库',
		'cmd.rebuildLinks': '重建关系图链接',
		'view.title': '库',
		'modal.pickType': '选择分类',
		'modal.search.placeholder': '按标题搜索…',
		'modal.searchLibrary': '搜索你的库…',
		'modal.noCategories': '请先在设置中添加分类',
		'modal.manualTitle': '新条目',
		'modal.manualCreate': '创建',
		'notice.created': '已创建：{name}',
		'notice.notFound': '没有可更新的内容',
		'notice.searching': '正在获取元数据…',
		'notice.linksRebuilt': '已重建关系图链接：{count}',
		'sort.name': 'A-Z',
		'sort.year': '年份',
		'sort.rating': '评分',
		'sort.date': '日期',
		'header.creator': '创作者',
		'header.years': '年份',
		'header.seasons': '季数',
		'header.genre': '类型',
		'header.myRating': '我的评分',
		'header.progress': '进度',
		'header.complete': '已完成',
		'settings.intro':
			'配置内容分类。从侧边栏图标打开“库”标签页以添加内容；笔记会根据其 frontmatter 中的 Type 字段归入分类。',
		'settings.omdb.name': 'OMDb API 密钥（可选）',
		'settings.omdb.desc':
			'用于自动填充电影和剧集的 IMDb 评分和元数据。获取密钥：https://www.omdbapi.com/apikey.aspx',
		'settings.omdb.placeholder': '例如：a1b2c3d4',
		'settings.section.categories': '分类',
		'settings.categories.desc':
			'每个分类显示 Type frontmatter 等于下方值的笔记。',
		'settings.category.name': '分类 {index}',
		'settings.category.desc': '显示名称、匹配的 Type 值和来源',
		'settings.category.name.placeholder': '名称（例如：电影）',
		'settings.category.type.placeholder': 'Type（例如：Movie）',
		'settings.category.folder': '文件夹',
		'settings.category.folder.placeholder': '例如：Media/Movies',
		'settings.category.manual': '手动 · 无来源',
		'settings.addCategory': '添加分类',
		'settings.newCategory': '新分类',
		'settings.section.example': '示例笔记',
		'settings.example.desc':
			'要将笔记归入某个分类，请在 frontmatter 中设置 Type 字段。'
	},
	ar: {
		'cmd.addContent': 'إضافة محتوى',
		'cmd.refresh': 'تحديث البيانات الوصفية للملاحظة الحالية',
		'cmd.searchLibrary': 'ابحث في مكتبتك',
		'cmd.openLibrary': 'فتح المكتبة',
		'cmd.rebuildLinks': 'إعادة بناء روابط الرسم البياني',
		'view.title': 'المكتبة',
		'modal.pickType': 'اختر فئة',
		'modal.search.placeholder': 'ابحث بالعنوان…',
		'modal.searchLibrary': 'ابحث في مكتبتك…',
		'modal.noCategories': 'أضف فئة في الإعدادات أولاً',
		'modal.manualTitle': 'إدخال جديد',
		'modal.manualCreate': 'إنشاء',
		'notice.created': 'تم الإنشاء: {name}',
		'notice.notFound': 'لا يوجد شيء للتحديث',
		'notice.searching': 'جارٍ جلب البيانات الوصفية…',
		'notice.linksRebuilt': 'تمت إعادة بناء روابط الرسم البياني: {count}',
		'sort.name': 'أ-ي',
		'sort.year': 'السنة',
		'sort.rating': 'التقييم',
		'sort.date': 'التاريخ',
		'header.creator': 'المُنشئ',
		'header.years': 'السنوات',
		'header.seasons': 'المواسم',
		'header.genre': 'النوع',
		'header.myRating': 'تقييمي',
		'header.progress': 'التقدّم',
		'header.complete': 'مكتمل',
		'settings.intro':
			'اضبط فئات المحتوى. افتح علامة تبويب المكتبة من الشريط الجانبي لإضافة محتوى؛ تُجمَّع الملاحظات في فئات حسب حقل Type في الـ frontmatter.',
		'settings.omdb.name': 'مفتاح OMDb API (اختياري)',
		'settings.omdb.desc':
			'يُستخدم لملء تقييم IMDb والبيانات الوصفية للأفلام والمسلسلات تلقائيًا. احصل على مفتاح من: https://www.omdbapi.com/apikey.aspx',
		'settings.omdb.placeholder': 'مثال: a1b2c3d4',
		'settings.section.categories': 'الفئات',
		'settings.categories.desc':
			'تعرض كل فئة الملاحظات التي يساوي فيها حقل Type القيمة أدناه.',
		'settings.category.name': 'الفئة {index}',
		'settings.category.desc': 'الاسم المعروض، وقيمة Type المطابقة، والمصدر',
		'settings.category.name.placeholder': 'الاسم (مثل: أفلام)',
		'settings.category.type.placeholder': 'Type (مثل: Movie)',
		'settings.category.folder': 'المجلد',
		'settings.category.folder.placeholder': 'مثل: Media/Movies',
		'settings.category.manual': 'يدوي · بدون مصدر',
		'settings.addCategory': 'إضافة فئة',
		'settings.newCategory': 'فئة جديدة',
		'settings.section.example': 'ملاحظة مثال',
		'settings.example.desc':
			'لإدراج ملاحظة في فئة، عيّن حقل Type في الـ frontmatter.'
	},
	he: {
		'cmd.addContent': 'הוסף תוכן',
		'cmd.refresh': 'רענן מטא-נתונים של הפתק הנוכחי',
		'cmd.searchLibrary': 'חפש בספרייה שלך',
		'cmd.openLibrary': 'פתח את הספרייה',
		'cmd.rebuildLinks': 'בנה מחדש קישורי גרף',
		'view.title': 'ספרייה',
		'modal.pickType': 'בחר קטגוריה',
		'modal.search.placeholder': 'חיפוש לפי כותרת…',
		'modal.searchLibrary': 'חפש בספרייה שלך…',
		'modal.noCategories': 'הוסף קטגוריה בהגדרות תחילה',
		'modal.manualTitle': 'רשומה חדשה',
		'modal.manualCreate': 'צור',
		'notice.created': 'נוצר: {name}',
		'notice.notFound': 'אין מה לעדכן',
		'notice.searching': 'מאחזר מטא-נתונים…',
		'notice.linksRebuilt': 'קישורי הגרף נבנו מחדש: {count}',
		'sort.name': 'א-ת',
		'sort.year': 'שנה',
		'sort.rating': 'דירוג',
		'sort.date': 'תאריך',
		'header.creator': 'יוצר',
		'header.years': 'שנים',
		'header.seasons': 'עונות',
		'header.genre': 'ז׳אנר',
		'header.myRating': 'הדירוג שלי',
		'header.progress': 'התקדמות',
		'header.complete': 'הושלם',
		'settings.intro':
			'הגדר קטגוריות תוכן. פתח את לשונית הספרייה מסרגל הצד כדי להוסיף תוכן; פתקים מקובצים לקטגוריות לפי שדה ה-Type ב-frontmatter.',
		'settings.omdb.name': 'מפתח OMDb API (אופציונלי)',
		'settings.omdb.desc':
			'משמש למילוי אוטומטי של דירוג IMDb ומטא-נתונים לסרטים וסדרות. קבל מפתח בכתובת: https://www.omdbapi.com/apikey.aspx',
		'settings.omdb.placeholder': 'לדוגמה: a1b2c3d4',
		'settings.section.categories': 'קטגוריות',
		'settings.categories.desc':
			'כל קטגוריה מציגה פתקים שבהם שדה ה-Type שווה לערך שלמטה.',
		'settings.category.name': 'קטגוריה {index}',
		'settings.category.desc': 'שם תצוגה, ערך Type תואם, ומקור',
		'settings.category.name.placeholder': 'שם (לדוגמה: סרטים)',
		'settings.category.type.placeholder': 'Type (לדוגמה: Movie)',
		'settings.category.folder': 'תיקייה',
		'settings.category.folder.placeholder': 'לדוגמה: Media/Movies',
		'settings.category.manual': 'ידני · ללא מקור',
		'settings.addCategory': 'הוסף קטגוריה',
		'settings.newCategory': 'קטגוריה חדשה',
		'settings.section.example': 'פתק לדוגמה',
		'settings.example.desc':
			'כדי לכלול פתק בקטגוריה, הגדר את שדה ה-Type ב-frontmatter.'
	}
}

export interface ICategory {
	name: string
	typeValue: string
	contentType: ContentType
	folder: string
}

export interface ILibrarySettings {
	categories: ICategory[]
	omdbApiKey: string
	googleBooksApiKey: string
	rawgApiKey: string
}

export const DEFAULT_SETTINGS: ILibrarySettings = {
	categories: [],
	omdbApiKey: '',
	googleBooksApiKey: '',
	rawgApiKey: ''
}
